// data.ts

export const userData = [
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
  {
    loginID: "user001",
    email: "user001@example.com",
    role: "Admin",
    kantorWilayah: "Jakarta",
    outlate: "Outlet A",
  },
  {
    loginID: "user002",
    email: "user002@example.com",
    role: "User",
    kantorWilayah: "Bandung",
    outlate: "Outlet B",
  },
];